### PUT request to update a patient entity
PUT http://lb-f810c8a3.elb.localhost.localstack.cloud:4004/api/patients/b1a850a7-892a-4bd9-8719-05b1ae60e5e0
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "John Doe UPDATED",
  "email": "hey_there@example.com",
  "address": "123 main street",
  "dateOfBirth": "1995-09-09"
}

###